### ISSUE TITLE
[Enhancement]: Equivalent testing action for non-GUI apps

### ISSUE THREAD

**Issue by jnsgruk** [snapcrafters/ci#17]
### What changes would you like?

This set of actions provides `get-screenshot` for GUI apps, but nothing for CLI apps. It would be good to include an equivalent so that CLI apps could be tested, and the output posted on the call for testing issue like that screenshots are. 

Something like:

```yaml
steps:
    - name: Test the snap
      uses: snapcrafters/ci/test-snap@main
      with:
        test-script: |
          # At this point, the revision under test is already installed in the environment
          snap run snap_name --version
          snap run snap_name do_something
```

Whatever the output of the test-script should then be added as a comment.
